import ast
import base64
import binascii
import hashlib
import hmac
import os
import re
import secrets
import subprocess
import sys
import tempfile
import time
from pathlib import Path

import httpx
from dotenv import load_dotenv
from fastapi import FastAPI, Header, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from sqlalchemy import create_engine, inspect, text

# Load the .env file from the project root.
project_root = Path(__file__).resolve().parent.parent
load_dotenv(project_root / ".env")

DB_PATH = project_root / "backend" / "app.db"
DATABASE_URL = os.getenv("DATABASE_URL")
AUTH_SECRET = os.getenv("AUTH_SECRET") or secrets.token_urlsafe(32)
TOKEN_TTL_SECONDS = 60 * 60 * 24 * 7
frontend_origins = [origin.strip() for origin in os.getenv("FRONTEND_ORIGINS", "http://localhost:5500,http://127.0.0.1:5500").split(",") if origin.strip()]
ENABLE_CODE_EXECUTION = os.getenv("ENABLE_CODE_EXECUTION", "false").lower() == "true"

if DATABASE_URL and DATABASE_URL.startswith(("postgres://", "postgresql://")) and "+" not in DATABASE_URL.split(":", 1)[0]:
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql+psycopg://", 1).replace("postgresql://", "postgresql+psycopg://", 1)

if DATABASE_URL:
    database_engine = create_engine(DATABASE_URL, pool_pre_ping=True)
else:
    database_engine = create_engine(
        f"sqlite:///{DB_PATH}",
        connect_args={"check_same_thread": False},
    )


def init_db():
    if not DATABASE_URL:
        DB_PATH.parent.mkdir(parents=True, exist_ok=True)

    id_definition = (
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if database_engine.dialect.name == "postgresql"
        else "INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    with database_engine.begin() as connection:
        connection.execute(text(f"""
            CREATE TABLE IF NOT EXISTS users (
                id {id_definition},
                name TEXT NOT NULL,
                email TEXT NOT NULL UNIQUE,
                password_hash TEXT NOT NULL,
                password_salt TEXT NOT NULL,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        """))

    user_columns = {column["name"] for column in inspect(database_engine).get_columns("users")}
    missing_columns = []
    if "password_salt" not in user_columns:
        missing_columns.append("password_salt TEXT")
    if "created_at" not in user_columns:
        missing_columns.append("created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP")

    for column_definition in missing_columns:
        with database_engine.begin() as connection:
            connection.execute(text(f"ALTER TABLE users ADD COLUMN {column_definition}"))


def hash_password(password: str, salt: str | None = None):
    if salt is None:
        salt = secrets.token_hex(16)
    derived = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt.encode("utf-8"), 100_000)
    return salt, base64.b64encode(derived).decode("utf-8")


def verify_password(password: str, salt: str, hashed_password: str) -> bool:
    _, derived = hash_password(password, salt)
    return hmac.compare_digest(derived, hashed_password)


def create_token(user_id: int) -> str:
    issued_at = int(time.time())
    payload = f"{user_id}:{issued_at}:{secrets.token_urlsafe(16)}"
    encoded_payload = base64.urlsafe_b64encode(payload.encode("utf-8")).decode("utf-8").rstrip("=")
    signature = hmac.new(AUTH_SECRET.encode("utf-8"), encoded_payload.encode("ascii"), hashlib.sha256).digest()
    encoded_signature = base64.urlsafe_b64encode(signature).decode("ascii").rstrip("=")
    return f"{encoded_payload}.{encoded_signature}"


def decode_token(token: str) -> int | None:
    try:
        encoded_payload, encoded_signature = token.split(".", 1)
        expected_signature = hmac.new(AUTH_SECRET.encode("utf-8"), encoded_payload.encode("ascii"), hashlib.sha256).digest()
        supplied_signature = base64.urlsafe_b64decode(encoded_signature + "=" * (-len(encoded_signature) % 4))
        if not hmac.compare_digest(supplied_signature, expected_signature):
            return None

        decoded = base64.urlsafe_b64decode(encoded_payload + "=" * (-len(encoded_payload) % 4)).decode("utf-8")
        user_id_text, issued_at_text, _ = decoded.split(":", 2)
        if int(time.time()) - int(issued_at_text) > TOKEN_TTL_SECONDS:
            return None
        user_id = int(user_id_text)
        return user_id
    except (ValueError, TypeError, UnicodeDecodeError, binascii.Error):
        return None


init_db()

app = FastAPI(title="CodeLens API")

# Allow the simple frontend to call this API during local development.
app.add_middleware(
    CORSMiddleware,
    allow_origins=frontend_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/")
def root():
    return {"name": "CodeLens API", "status": "ok", "docs": "/docs", "health": "/api/health"}


def build_local_review(code: str, language: str, instructions: str) -> str:
    """Provide a simple, reliable review when the external AI service is unavailable."""
    summary = f"This {language} code is short, readable, and shows a clear goal."
    bugs = ["I did not find a major syntax issue from the snippet, but edge cases deserve attention."]
    quality = "The structure is clean and the naming is understandable, which helps beginners follow the logic."
    complexity = "The loop-based approach is usually O(n) time and O(1) extra space if it only keeps a few variables."
    improvements = [
        "Add a quick test for an empty list or a single-item list.",
        "Be explicit about the expected behavior for invalid or empty inputs.",
    ]

    try:
        tree = ast.parse(code)
        function_names = [node.name for node in ast.walk(tree) if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))]
        if function_names:
            summary = f"This {language} code defines a function named {function_names[0]} and tries to solve a small problem in a clear way."

        if "max_value = 0" in code and "if number > max_value" in code:
            bugs = [
                "If the input list is empty, the function will return 0 instead of handling that edge case. This can hide real problems in the data.",
                "Using a starting value like 0 can also be wrong when the input contains negative numbers, because a negative number may not be treated as a valid maximum.",
            ]
            improvements = [
                "Initialize the maximum value from the first item in the list instead of a fixed number.",
                "Add a check for empty input so the function behaves predictably.",
            ]
            quality = "The code is easy to read, but the starting condition should be more defensive for edge cases."
            complexity = "The logic is still O(n) time because it checks each entry once, but the memory use remains O(1)."
    except SyntaxError:
        bugs = ["The code may contain a syntax or parsing problem, so it should be checked before running it in a real project."]
        quality = "The code is not currently parseable, so readability cannot be fully assessed until the syntax issue is fixed."
        improvements = [
            "Run the code in Python to catch the exact syntax problem.",
            "Fix the error before moving on to deeper review suggestions.",
        ]

    review = (
        "1. Summary\n"
        f"{summary}\n\n"
        "2. Bugs and risks\n"
        + "\n".join(f"- {issue}" for issue in bugs)
        + "\n\n"
        "3. Code quality\n"
        f"{quality}\n\n"
        "4. Time and space complexity\n"
        f"{complexity}\n\n"
        "5. Simple improvements\n"
        + "\n".join(f"- {item}" for item in improvements)
    )

    if instructions:
        review = review + f"\n\nHelpful focus: {instructions}"

    return review


class ReviewRequest(BaseModel):
    code: str = Field(min_length=1, max_length=20000)
    language: str = "python"
    instructions: str = "Explain the important problems like I am a beginner."


class ReviewResponse(BaseModel):
    review: str
    model: str


class TestGeneratorRequest(BaseModel):
    code: str = Field(min_length=1, max_length=20000)
    language: str = "python"


class TestGeneratorResponse(BaseModel):
    tests: str
    model: str


class ExplainCodeRequest(BaseModel):
    code: str = Field(min_length=1, max_length=20000)
    level: str = "beginner"
    language: str = "python"


class ExplainCodeResponse(BaseModel):
    explanation: str
    model: str


class BugVerificationRequest(BaseModel):
    code: str = Field(min_length=1, max_length=20000)
    language: str = "python"


class BugVerificationResponse(BaseModel):
    summary: str
    verification: str


class StaticAnalysisRequest(BaseModel):
    code: str = Field(min_length=1, max_length=20000)
    language: str = "python"


class StaticAnalysisResponse(BaseModel):
    summary: str
    analysis: str


class ComplexityAnalysisRequest(BaseModel):
    code: str = Field(min_length=1, max_length=20000)
    language: str = "python"


class ComplexityAnalysisResponse(BaseModel):
    complexity: str


class OptimizationRequest(BaseModel):
    code: str = Field(min_length=1, max_length=20000)
    language: str = "python"


class OptimizationResponse(BaseModel):
    suggestion: str


class QualityScoreRequest(BaseModel):
    code: str = Field(min_length=1, max_length=20000)
    language: str = "python"


class QualityScoreResponse(BaseModel):
    score: int
    summary: str


class RunRequest(BaseModel):
    code: str = Field(min_length=1, max_length=20000)


class RunResponse(BaseModel):
    output: str
    error: str
    execution_time: float
    timed_out: bool


class RegisterRequest(BaseModel):
    name: str = Field(min_length=2, max_length=80)
    email: str = Field(min_length=4, max_length=120)
    password: str = Field(min_length=8, max_length=128)


class LoginRequest(BaseModel):
    email: str = Field(min_length=4, max_length=120)
    password: str = Field(min_length=8, max_length=128)


class UserPublic(BaseModel):
    id: int
    name: str
    email: str
    created_at: str | None = None


class AuthResponse(BaseModel):
    token: str
    user: UserPublic


def public_user(row) -> UserPublic:
    user_data = dict(row)
    if user_data.get("created_at") is not None:
        user_data["created_at"] = str(user_data["created_at"])
    return UserPublic(**user_data)


@app.get("/api/health")
def health_check():
    return {"status": "ok"}


@app.post("/api/auth/register", response_model=AuthResponse)
def register_user(request: RegisterRequest):
    email = request.email.strip().lower()
    name = request.name.strip()
    if len(name) < 2:
        raise HTTPException(status_code=400, detail="Name must contain at least two non-space characters.")
    if "@" not in email or email.startswith("@") or email.endswith("@"):
        raise HTTPException(status_code=400, detail="Invalid email address.")

    with database_engine.begin() as conn:
        existing = conn.execute(text("SELECT id FROM users WHERE email = :email"), {"email": email}).mappings().first()
        if existing:
            raise HTTPException(status_code=409, detail="An account with this email already exists.")

        salt, password_hash = hash_password(request.password)
        cursor = conn.execute(
            text("INSERT INTO users (name, email, password_hash, password_salt) VALUES (:name, :email, :password_hash, :password_salt) RETURNING id"),
            {"name": name, "email": email, "password_hash": password_hash, "password_salt": salt},
        )
        user_id = cursor.scalar_one()
        user_row = conn.execute(
            text("SELECT id, name, email, created_at FROM users WHERE id = :id"),
            {"id": user_id},
        ).mappings().first()

    token = create_token(user_id)
    return AuthResponse(
        token=token,
        user=public_user(user_row),
    )


@app.post("/api/auth/login", response_model=AuthResponse)
def login_user(request: LoginRequest):
    email = request.email.strip().lower()

    with database_engine.begin() as conn:
        user_row = conn.execute(
            text("SELECT id, name, email, password_hash, password_salt, created_at FROM users WHERE email = :email"),
            {"email": email},
        ).mappings().first()

    if not user_row:
        raise HTTPException(status_code=401, detail="Invalid email or password.")

    if not user_row["password_salt"] or not verify_password(request.password, user_row["password_salt"], user_row["password_hash"]):
        raise HTTPException(status_code=401, detail="Invalid email or password.")

    token = create_token(user_row["id"])
    return AuthResponse(
        token=token,
        user=UserPublic(
            id=user_row["id"],
            name=user_row["name"],
            email=user_row["email"],
            created_at=str(user_row["created_at"]),
        ),
    )


@app.get("/api/auth/me", response_model=UserPublic)
def get_current_user(authorization: str | None = Header(default=None, alias="Authorization")):
    if not authorization or not authorization.startswith("Bearer "):
        raise HTTPException(status_code=401, detail="Missing or invalid auth token.")

    token = authorization.split(" ", 1)[1]
    user_id = decode_token(token)
    if user_id is None:
        raise HTTPException(status_code=401, detail="Invalid auth token.")

    with database_engine.begin() as conn:
        row = conn.execute(
            text("SELECT id, name, email, created_at FROM users WHERE id = :id"),
            {"id": user_id},
        ).mappings().first()

    if row is None:
        raise HTTPException(status_code=401, detail="User not found.")

    return public_user(row)


def build_local_test_cases(code: str, language: str) -> str:
    """Generate simple, beginner-friendly unit tests based on a function snippet."""
    stripped = code.strip()
    function_name = "sample_function"
    if "def " in stripped:
        match = re.search(r"def\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(", stripped)
        if match:
            function_name = match.group(1)

    if "factorial" in function_name.lower() or "factorial" in code.lower():
        tests = [
            f"def test_{function_name}_zero_case():",
            "    result = " + function_name + "(0)",
            "    assert result == 1",
            "",
            f"def test_{function_name}_small_number():",
            "    result = " + function_name + "(5)",
            "    assert result == 120",
            "",
            f"def test_{function_name}_one_case():",
            "    result = " + function_name + "(1)",
            "    assert result == 1",
        ]
        return "\n".join(tests)

    tests = [
        f"def test_{function_name}_basic_case():",
        "    result = " + function_name + "([3, 8, 1, 6])",
        "    assert result == 8",
        "",
        f"def test_{function_name}_single_value():",
        "    result = " + function_name + "([42])",
        "    assert result == 42",
        "",
        f"def test_{function_name}_negative_numbers():",
        "    result = " + function_name + "([-5, -2, -9, -1])",
        "    assert result == -1",
    ]

    if "raise ValueError" in code or "ValueError" in code:
        tests.extend([
            "",
            f"def test_{function_name}_empty_list_raises_error():",
            "    try:",
            "        " + function_name + "([])",
            "    except ValueError:",
            "        pass",
            "    else:",
            "        raise AssertionError('Expected ValueError for an empty list')",
        ])

    return "\n".join(tests)


@app.post("/api/generate-tests", response_model=TestGeneratorResponse)
def generate_tests(request: TestGeneratorRequest):
    if request.language.lower() != "python":
        return TestGeneratorResponse(
            tests="This feature currently supports Python only.",
            model="local-test-generator",
        )

    tests = build_local_test_cases(request.code, request.language)
    return TestGeneratorResponse(tests=tests, model="local-test-generator")


def build_local_explanation(code: str, level: str, language: str) -> str:
    """Generate a readable explanation for code snippets without requiring an external LLM."""
    level_name = (level or "beginner").lower()
    function_names = re.findall(r"def\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(", code)
    primary_name = function_names[0] if function_names else "the function"

    if not function_names:
        explanation = [
            f"What this {language} code does:",
            "This code does not define a function. It is a short script that assigns values, displays output, and updates the values before displaying them again.",
            "",
            "How it works:",
            "- The variables are assigned their initial values.",
            "- The first print statement displays the values in their original order.",
            "- The assignment swaps the values between the variables.",
            "- The second print statement displays the updated order.",
            "",
            "Important parts:",
            "- Variables hold the values while the script runs.",
            "- print sends the current values to the console.",
            "- The statements execute from top to bottom.",
            "",
            "Algorithm used:",
            "The script follows a direct sequence of assignments and output statements.",
            "",
            "Time complexity:",
            "O(1), because it performs a fixed number of operations.",
            "",
            "Space complexity:",
            "O(1), because it stores only a fixed number of variables.",
        ]
        return "\n".join(explanation)

    explanation = [
        f"What this {language} code does:",
        f"This code defines {primary_name} and uses it to process values in a simple, step-by-step way.",
        "",
        "How it works:",
        "- The function is defined once with a clear name.",
        "- It receives input values from the caller.",
        "- It performs a small calculation or check inside the function body.",
        "- It returns the final result to the caller.",
        "",
        "Important parts:",
        "- Parameters are the values passed into the function.",
        "- The return statement sends the output back.",
        "- The logic is written in plain Python statements that run in order.",
        "",
        "Algorithm used:",
        "The program follows a straightforward sequential algorithm. It reads each input, performs the required work, and produces a final answer.",
        "",
        "Time complexity:",
        "For small scripts like this, the runtime is typically linear or near-linear, depending on the number of operations inside the loop or condition.",
        "",
        "Space complexity:",
        "The function uses a small amount of extra memory because it stores only a few local variables during execution.",
    ]

    if level_name == "technical":
        explanation = [
            f"What this {language} code does:",
            f"{primary_name} encapsulates a procedural transformation over input data and exposes a deterministic result based on the provided arguments.",
            "",
            "How it works:",
            "- The function declaration binds a callable object to a name in the local module namespace.",
            "- Parameters are assigned at call time and used during evaluation of the function body.",
            "- Statements inside the body execute sequentially, often applying logic to each item or condition.",
            "- A return value communicates the computed result to the caller.",
            "",
            "Important functions and logic:",
            "- The function body contains the core algorithm.",
            "- Control flow operations direct execution based on conditions.",
            "- Return values provide the programmatic output used by the rest of the application.",
            "",
            "Algorithm used:",
            "This is a procedural implementation that follows a simple iteration or evaluation pattern. The algorithm is deterministic and depends on the given input values.",
            "",
            "Time complexity:",
            "The complexity depends on the number of operations executed. If the function loops through a list, the runtime is typically O(n) in the common case.",
            "",
            "Space complexity:",
            "The additional memory footprint remains small because only a few variables are created for the calculation.",
        ]

    return "\n".join(explanation)


@app.post("/api/explain-code", response_model=ExplainCodeResponse)
def explain_code(request: ExplainCodeRequest):
    if request.language.lower() != "python":
        return ExplainCodeResponse(
            explanation="This explanation feature currently supports Python code only.",
            model="local-explainer",
        )

    explanation = build_local_explanation(request.code, request.level, request.language)
    return ExplainCodeResponse(explanation=explanation, model="local-explainer")


def build_bug_verification(code: str, language: str) -> tuple[str, str]:
    summary = f"Bug verification found no obvious crash in this {language} snippet, but there are a few edge cases worth checking."
    verification = "Verification: the logic has been checked for common failure patterns such as empty input, invalid values, and boundary conditions."

    lowered = code.lower()
    if "max_value = 0" in lowered and "if number > max_value" in lowered:
        summary = "Bug verification found a likely bug: the code initializes the maximum value to 0, which fails for negative numbers and empty input."
        verification = "Verification: if the list contains negative values, the result can be wrong; if the list is empty, the function may return 0 instead of raising a clear error."
    elif "value % 2 == 0" in lowered:
        summary = "Bug verification found a normal parity check with no immediate logic bug, but it should be validated for non-numeric input."
        verification = "Verification: the function is likely correct for integers, but it should guard against strings or None values to avoid unexpected crashes."

    return summary, verification


@app.post("/api/bug-verification", response_model=BugVerificationResponse)
def bug_verification(request: BugVerificationRequest):
    summary, verification = build_bug_verification(request.code, request.language)
    return BugVerificationResponse(summary=summary, verification=verification)


def build_static_analysis(code: str, language: str) -> tuple[str, str]:
    summary = f"Static analysis for this {language} snippet shows a readable function structure with a few checks worth tightening."
    analysis = "Static analysis: the code is structurally sound, but the function could benefit from clearer validation, simpler branches, and stronger edge-case handling."

    if "for " in code and "if " in code:
        analysis = "Static analysis: this code contains iteration and a conditional branch. The logic is straightforward, but a guard for empty or malformed input would make it more robust."
    if "try:" in code or "except" in code:
        summary = f"Static analysis for this {language} snippet shows defensive programming patterns, which helps prevent runtime failures."
        analysis = "Static analysis: error handling is present, which is a good sign. The remaining risk is unclear behavior when unexpected values appear."

    return summary, analysis


@app.post("/api/static-analysis", response_model=StaticAnalysisResponse)
def static_analysis(request: StaticAnalysisRequest):
    summary, analysis = build_static_analysis(request.code, request.language)
    return StaticAnalysisResponse(summary=summary, analysis=analysis)


def build_complexity_analysis(code: str, language: str) -> str:
    lowered = code.lower()
    if "for " in lowered and "for " in lowered.lower().split("for ", 1)[1]:
        return f"Time complexity: O(n^2) in the worst case because nested loops or repeated checks increase the work as the input grows. Space complexity: O(1) unless extra data structures are created."
    if "for " in lowered:
        return f"Time complexity: O(n) because the code processes each input item once. Space complexity: O(1) for the simple loop variables used in this {language} function."
    return f"Time complexity: O(1) for the current straightforward logic. Space complexity: O(1) because the function stores only a few local values."


@app.post("/api/complexity-analysis", response_model=ComplexityAnalysisResponse)
def complexity_analysis(request: ComplexityAnalysisRequest):
    complexity = build_complexity_analysis(request.code, request.language)
    return ComplexityAnalysisResponse(complexity=complexity)


def build_optimization_suggestion(code: str, language: str) -> str:
    lowered = code.lower()
    if "for " in lowered and "if " in lowered:
        return "Optimization suggestion: reduce repeated work by simplifying branches, using early returns, and keeping the algorithm focused on the actual task instead of re-checking conditions."
    if "sum(" in lowered or "sum" in lowered:
        return "Optimization suggestion: if the logic is just summing values, use a built-in operation or a more direct method to reduce noise and improve clarity."
    return f"Optimization suggestion: the current {language} implementation is already simple, and the best improvement is to add validation and avoid repeated work where possible."


@app.post("/api/optimize-code", response_model=OptimizationResponse)
def optimize_code(request: OptimizationRequest):
    suggestion = build_optimization_suggestion(request.code, request.language)
    return OptimizationResponse(suggestion=suggestion)


def build_quality_score(code: str, language: str) -> tuple[int, str]:
    score = 82
    lowered = code.lower()
    if "def " not in code:
        score -= 20
    if "return " not in code:
        score -= 10
    if "if " in code:
        score += 6
    if "for " in code:
        score += 4
    if "pass" in lowered or "todo" in lowered:
        score -= 18
    if "raise valueerror" in lowered or "assert" in lowered:
        score += 8
    if "print(" in lowered:
        score -= 5
    if "try:" in code or "except" in code:
        score += 8
    score = max(0, min(100, score))
    summary = f"Quality score: {score}/100 for this {language} snippet. The code is readable and structured, but edge-case handling and validation can still improve its reliability."
    return score, summary


@app.post("/api/quality-score", response_model=QualityScoreResponse)
def quality_score(request: QualityScoreRequest):
    score, summary = build_quality_score(request.code, request.language)
    return QualityScoreResponse(score=score, summary=summary)


@app.post("/api/run", response_model=RunResponse)
def run_code(request: RunRequest):
    """Run a Python snippet for local development with a short time limit."""
    if not ENABLE_CODE_EXECUTION:
        raise HTTPException(status_code=503, detail="Code execution is disabled on this server.")

    started_at = time.perf_counter()

    try:
        with tempfile.TemporaryDirectory() as temporary_directory:
            file_path = Path(temporary_directory) / "user_code.py"
            file_path.write_text(request.code, encoding="utf-8")
            with tempfile.TemporaryFile(mode="w+b") as stdout_file, tempfile.TemporaryFile(mode="w+b") as stderr_file:
                process = subprocess.Popen(
                    [sys.executable, "-I", str(file_path)],
                    stdout=stdout_file,
                    stderr=stderr_file,
                    cwd=temporary_directory,
                )
                try:
                    process.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    process.kill()
                    process.wait()
                    return RunResponse(
                        output="",
                        error="Execution stopped after 5 seconds.",
                        execution_time=round(time.perf_counter() - started_at, 3),
                        timed_out=True,
                    )

                stdout_file.seek(max(0, stdout_file.tell() - 10000))
                stderr_file.seek(max(0, stderr_file.tell() - 10000))
                output = stdout_file.read().decode("utf-8", errors="replace").replace("\r\n", "\n")
                error = stderr_file.read().decode("utf-8", errors="replace").replace("\r\n", "\n")
    except subprocess.TimeoutExpired as error:
        return RunResponse(
            output=error.stdout or "",
            error="Execution stopped after 5 seconds.",
            execution_time=round(time.perf_counter() - started_at, 3),
            timed_out=True,
        )

    return RunResponse(
        output=output,
        error=error,
        execution_time=round(time.perf_counter() - started_at, 3),
        timed_out=False,
    )


@app.post("/api/review", response_model=ReviewResponse)
async def review_code(request: ReviewRequest):
    api_key = os.getenv("GEMINI_API_KEY")
    model = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")

    if not api_key:
        return ReviewResponse(
            review=build_local_review(request.code, request.language, request.instructions),
            model="local-review-fallback",
        )

    prompt = f"""You are a patient code reviewer for beginners.

Review this {request.language} code.

{request.code}

Instructions: {request.instructions}

Return a clear review with these headings:
1. Summary
2. Bugs and risks
3. Code quality
4. Time and space complexity
5. Simple improvements

If there are no problems in a section, say so. Use plain text and do not use markdown tables."""

    url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent"
    payload = {"contents": [{"parts": [{"text": prompt}]}]}

    try:
        async with httpx.AsyncClient(timeout=45) as client:
            response = await client.post(url, params={"key": api_key}, json=payload)
            response.raise_for_status()
    except (httpx.HTTPStatusError, httpx.RequestError):
        fallback_review = build_local_review(request.code, request.language, request.instructions)
        return ReviewResponse(review=fallback_review, model="local-review-fallback")

    data = response.json()
    candidates = data.get("candidates", [])
    if not candidates:
        return ReviewResponse(
            review=build_local_review(request.code, request.language, request.instructions),
            model="local-review-fallback",
        )

    review_text = candidates[0].get("content", {}).get("parts", [{}])[0].get("text", "")
    if not review_text:
        return ReviewResponse(
            review=build_local_review(request.code, request.language, request.instructions),
            model="local-review-fallback",
        )

    return ReviewResponse(review=review_text, model=model)
